### ISSUE TITLE
Unable to install filterregistrations plugin

### ISSUE THREAD

**Issue by houdini69** [JohnXLivingston/peertube-plugin-filterregistrations#1]
Got this error
`﻿error[8/11/2022, 9:31:20 AM] Cannot install plugin peertube-plugin-filterregistrations, removing it...

{
  "err": {
    "stack": "Error: Cannot find module 'whois-json'\nRequire stack:\n- /var/www/peertube/storage/plugins/node_modules/peertube-plugin-filterregistrations/main.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/plugins/plugin-manager.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/plugins/hooks.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/model-loaders/video.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/model-loaders/index.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/actors/get.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/actors/index.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/share.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/videos/federate.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/videos/index.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/schedulers/videos-redundancy-scheduler.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/job-queue/handlers/video-redundancy.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/job-queue/job-queue.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/job-queue/index.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/send/shared/send-utils.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/send/send-follow.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/send/send-accept.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/send/index.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/video/video-channel.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/redundancy/video-redundancy.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/video/video-file.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/hls.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/live/live-segment-sha-store.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/live/index.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/user/user.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/live/live-manager.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/video/video.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/actor/actor.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/account/actor-custom-page.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/initializers/database.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/helpers/database-utils.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/video/thumbnail.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/abuse/abuse.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/abuse/video-comment-abuse.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/video/video-comment.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/send/send-delete.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/account/account.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/application/application.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/initializers/checker-after-init.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:746:27)\n    at Module.require (internal/modules/cjs/loader.js:974:19)\n    at require (internal/modules/cjs/helpers.js:101:18)\n    at Object.<anonymous> (/var/www/peertube/storage/plugins/node_modules/peertube-plugin-filterregistrations/main.js:1:77)\n    at Module._compile (internal/modules/cjs/loader.js:1085:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)\n    at Module.load (internal/modules/cjs/loader.js:950:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:790:12)\n    at Module.require (internal/modules/cjs/loader.js:974:19)\n    at require (internal/modules/cjs/helpers.js:101:18)\n    at PluginManager.<anonymous> (/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/plugins/plugin-manager.js:319:29)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-v4.2.2/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-v4.2.2/node_modules/tslib/tslib.js:113:16)\n    at PluginManager.registerPlugin (/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/plugins/plugin-manager.js:315:24)\n    at PluginManager.<anonymous> (/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/plugins/plugin-manager.js:288:43)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/peertube/versions/peertube-v4.2.2/node_modules/tslib/tslib.js:114:62)",
    "message": "Cannot find module 'whois-json'\nRequire stack:\n- /var/www/peertube/storage/plugins/node_modules/peertube-plugin-filterregistrations/main.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/plugins/plugin-manager.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/plugins/hooks.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/model-loaders/video.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/model-loaders/index.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/actors/get.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/actors/index.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/share.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/videos/federate.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/videos/index.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/schedulers/videos-redundancy-scheduler.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/job-queue/handlers/video-redundancy.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/job-queue/job-queue.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/job-queue/index.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/send/shared/send-utils.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/send/send-follow.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/send/send-accept.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/send/index.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/video/video-channel.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/redundancy/video-redundancy.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/video/video-file.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/hls.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/live/live-segment-sha-store.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/live/index.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/user/user.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/live/live-manager.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/video/video.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/actor/actor.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/account/actor-custom-page.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/initializers/database.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/helpers/database-utils.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/video/thumbnail.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/abuse/abuse.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/abuse/video-comment-abuse.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/video/video-comment.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/send/send-delete.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/account/account.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/models/application/application.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server/initializers/checker-after-init.js\n- /var/www/peertube/versions/peertube-v4.2.2/dist/server.js",
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
      "/var/www/peertube/storage/plugins/node_modules/peertube-plugin-filterregistrations/main.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/plugins/plugin-manager.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/plugins/hooks.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/model-loaders/video.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/model-loaders/index.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/actors/get.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/actors/index.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/share.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/videos/federate.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/videos/index.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/schedulers/videos-redundancy-scheduler.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/job-queue/handlers/video-redundancy.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/job-queue/job-queue.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/job-queue/index.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/send/shared/send-utils.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/send/send-follow.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/send/send-accept.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/send/index.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/models/video/video-channel.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/models/redundancy/video-redundancy.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/models/video/video-file.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/hls.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/live/live-segment-sha-store.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/live/index.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/models/user/user.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/live/live-manager.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/models/video/video.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/models/actor/actor.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/models/account/actor-custom-page.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/initializers/database.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/helpers/database-utils.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/models/video/thumbnail.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/models/abuse/abuse.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/models/abuse/video-comment-abuse.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/models/video/video-comment.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/lib/activitypub/send/send-delete.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/models/account/account.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/models/application/application.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server/initializers/checker-after-init.js",
      "/var/www/peertube/versions/peertube-v4.2.2/dist/server.js"
    ]
  }
}`

on a PeerTube version 4.2.2 server with node version v14.20.0

**Comment by JohnXLivingston** [comment]
Oh, I forgot to remove a line from the plugin I copied/pasted to init this one.
So, it worked for me because I had the other plugin installed (and so I had the whois-json library).

This is fixed in https://github.com/JohnXLivingston/peertube-plugin-filterregistrations/commit/0b2e2541503b4d618879c548d0bf474cc8c0108f , and I just released the v0.1.2.

Sorry for that, and thanks for the report.
